name: Build and Upload to JFrog

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # or 6.0.x or your version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet publish -c Release -o ./publish

    - name: Zip published output
      run: zip -r HelloWorld.zip ./publish

    - name: Install JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3

    - name: Configure JFrog CLI
      env:
        JF_URL: https://trialmp088s.jfrog.io
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      run: |
        jf c add my-jfrog \
          --url=$JF_URL \
          --access-token=$JF_ACCESS_TOKEN \
          --interactive=false

    - name: Upload zip to JFrog
      run: jf rt u "HelloWorld.zip" "local-generic-local/HelloWorld/"
